name: IO actions
'on':
  pull_request:
jobs:
  io-app-test:
    name: IO app test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: yarn
        env:
          RUNNER_TEMP: /tmp
      - name: Run test on every builder directory
        uses: vtex/action-io-app-test@master
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: yarn
        env:
          RUNNER_TEMP: /tmp
      - name: Lint project
        uses: vtex/action-lint@master
